# Generated by Django 6.0.1 on 2026-08-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
